# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.output_dir}/${run_name}/
sweep:
  dir: ${paths.output_dir}/${run_name}/multiruns
  subdir: ${hydra.job.num}
  