# Path to the directory where checkpoints and logs will be saved
output_dir: /scratch/sshfs3/ML-AI/world_model_project/output_data/next_token_predictor

# Path to the directory where data is located
data_dir: /scratch/sshfs3/ML-AI/world_model_project/data_raw/nuscenes

nuscenes_pickle_path: /scratch/sshfs3/ML-AI/world_model_project/data_preprocessed/nuscenes_pickle/trainval_data.pkl

quantized_nuscenes_root_dir: /scratch/sshfs3/ML-AI/world_model_project/data_preprocessed/nuscenes_tokenized/VQGAN_ImageNet_f16_1024/

