defaults:
  - default

## motional
nuscenes:
  images_rootdir: $cya_ALL_CCFRSCRATCH/nuscenes
  train_pickle: $cya_ALL_CCFRWORK/cleaned_trajectory_pickle/nuscenes_train_data_cleaned.pkl
  val_pickle: $cya_ALL_CCFRWORK/cleaned_trajectory_pickle/nuscenes_val_data_cleaned.pkl

nuplan:
  images_rootdir: $cya_ALL_CCFRSCRATCH/nuplan/frames
  train_pickle: $cya_ALL_CCFRWORK/cleaned_trajectory_pickle/nuplan_train_data_cleaned.pkl
  val_pickle: $cya_ALL_CCFRWORK/cleaned_trajectory_pickle/nuplan_val_data_cleaned.pkl
