defaults:
  - model_summary
  - tqdm_progress_bar
  - learning_rate_monitor
  - device_stats_monitor
  - _self_

before_drop_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "${paths.output_dir}/${name}/checkpoints/"
  filename: "before_drop_{epoch:03d}_{step:010d}"
  every_n_train_steps: 6543 # 7269 - 726 

every_quarter_epoch_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "${paths.output_dir}/${name}/checkpoints/"
  filename: "quarters_{epoch:03d}_{step:010d}"
  every_n_train_steps: 1817
  save_top_k: -1

last_hours_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "${paths.output_dir}/${name}/checkpoints/"
  filename: "last_hours_{epoch:03d}_{step:010d}"
  save_top_k: 1
  train_time_interval:
    _target_: datetime.timedelta
    hours: 1
