defaults:
  - model_summary
  - tqdm_progress_bar
  - learning_rate_monitor
  - device_stats_monitor
  - _self_

before_drop_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "${paths.output_dir}/${name}/checkpoints/"
  filename: "before_drop_epoch_{epoch:03d}_step_{step:010d}"
  every_n_train_steps: 8871

every_quarter_epoch_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "${paths.output_dir}/${name}/checkpoints/"
  filename: "quarters_epoch_{epoch:03d}_step_{step:010d}"
  every_n_train_steps: 2464
  save_top_k: -1

last_hours_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "${paths.output_dir}/${name}/checkpoints/"
  filename: "last_hours_epoch_{epoch:03d}_step_{step:010d}"
  save_top_k: 1
  train_time_interval:
    _target_: datetime.timedelta
    hours: 8
