defaults:
  - model_checkpoint
  - model_summary
  - tqdm_progress_bar
  - learning_rate_monitor
  - device_stats_monitor
  - _self_

model_checkpoint:
  dirpath: "${paths.output_dir}/${run_name}/checkpoints/"
  filename: "epoch_{epoch:03d}_val_perplexity_{val/perplexity:.4f}"
  monitor: "val/perplexity"
  mode: "min"
