# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelSummary.html

model_summary:
  _target_: lightning.pytorch.callbacks.ModelSummary
  max_depth: 2 # the maximum depth of layer nesting that the summary will include
