# @package _global_

defaults:
  - _self_
  - paths: default
  - hydra: default

name: "inference" # used by hydra in case of error looging

# The directory where model logs are stored (the folder `checkpoints`, `tensorboard`, etc.. are under it).
model_log_dir: ???

# The name to the model checkpoint file (e.g., `epoch_006_val_perplexity_365.0459.ckpt`).
checkpoint_name: ???

# Path to the directory where the predicted tokens data will be stored. 
# The directory does not need to exist beforehand.
output_dir: ${paths.output_dir}

# The number of sequences to samples
# i.e., then number of possible future sequence to generate
nb_samplings: 2

save_logits: False

pickle_name: nuplan_val_front_camera_data.pkl

dataset_config:
  data_root_dir: ${paths.data_root_dir}
  quantized_data_root_dir: ${paths.quantized_data_root_dir}
  extracted_sequence_length: 39
  context_to_prediction_index: 16
  nb_context_frames: 4
  nb_prediction_frames: 6
  load_image: False
  subsampling_factor: 2

dataloader_config: 
  batch_size: 4
  num_workers: 4
  pin_memory: True
  prefetch_factor: 2
  shuffle: False
  drop_last: False

samplers:
  top5: 
    _target_: world_model.utils.generation.TopKSampler
    k: 5

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: False
