# @package _global_

# uses only 10 batches of the training/validation/test data

defaults:
  - default
  - override /callbacks: callbacks_training.yaml
  - override /logger: many_loggers.yaml

trainer:
  max_epochs: 10
  limit_train_batches: 50
  limit_val_batches: 3
  limit_test_batches: 3
  strategy: auto
  accelerator: gpu
  devices: 1

data:
  dataloader_params:
    num_workers: 6
    pin_memory: True
    shuffle: null
    prefetch_factor: 1