# @package _global_


defaults:
  - default
  - override /callbacks: callbacks_debug.yaml
  - override /logger: tensorboard.yaml


# overfits to 1 batches
trainer:
  max_epochs: 800
  overfit_batches: 1
  log_every_n_steps: 1
  strategy: auto
  accelerator: gpu
  devices: 1
  check_val_every_n_epoch: 100000 # can't be zero or throws error

data:
  dataloader_params:
    num_workers: 3
    batch_size: 1
    pin_memory: True
    shuffle: False
    prefetch_factor: 1
