# @package _global_

# uses only 10 batches of the training/validation/test data

defaults:
  - default
  - override /callbacks: callbacks_debug.yaml
  - override /logger: tensorboard.yaml

trainer:
  max_epochs: 10
  limit_train_batches: 50
  limit_val_batches: 50
  limit_test_batches: 50
  log_every_n_steps: 10
  strategy: auto
  accelerator: gpu
  devices: 1

data:
  dataloader_params:
    num_workers: 4
    batch_size: 2
    pin_memory: True
    prefetch_factor: 3