# @package _global_

# overfits to 3 batches

defaults:
  - default
  - override /callbacks: callbacks_debug.yaml
  - override /logger: tensorboard.yaml

trainer:
  max_epochs: 20
  overfit_batches: 1
  log_every_n_steps: 1
